name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0
          registry-url: 'https://registry.npmjs.org'
      - name: Setup
        run: npm i -g pnpm
      - name: Install Dependencies
        run: pnpm install && pnpm build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VINICUNCA_DOCS }}'
          projectId: vinicunca-docs
          channelId: live
  
